### ISSUE TITLE
Content scrollable

### ISSUE THREAD

**Issue by quetool** [CaliCastle/PopMenu#10]
## ✔️ Issue Checklist

- [x] I have updated PopMenu to the latest version.
- [X] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [X] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [X] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## ✍🏻 Issue Description
Is it possible to make actions scrollable inside menu? I mean, what happens if I have many many actions?

## 💻 Environment

- **iOS Version**: [iOS VERSION]
- **Xcode Version**: [XCODE VERSION]
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Simulator?**: [YES] or [NO]

**Comment by CaliCastle** [comment]
That's a good idea actually, I didn't think about having too many options in the menu but sure, I'll add it to the list.

Thank you!

**Comment by quetool** [comment]
@CaliCastle Thanks to you. This is a great library :)

**Comment by CaliCastle** [comment]
Hi,

The suggested enhancement is completed in v2.1.1, let me know if there's any issue or bug, thanks again!
