### ISSUE TITLE
I don't have any issue, just a request , how can I open a ViewController when I press on PopMenu button?

### ISSUE THREAD

**Issue by nsoud** [CaliCastle/PopMenu#11]
hi;
I don't have any issue, just a request , how can I open a ViewController when I press on PopMenu button?
Kind Regards;

**Comment by CaliCastle** [comment]
Hey,

Can’t you push a new ViewController when the menu is dismissed?

Example: (in your viewcontroller class)
let action1 = PopMenuDefaultAction(title: "Action 1", didSelect: { action in
    self.navigationController.push(viewController);
})
