### ISSUE TITLE
Not support landscape

### ISSUE THREAD

**Issue by LayChan** [CaliCastle/PopMenu#12]
First of all thank you for your contribution, I have a pimping claim: that be hope it can support the landscape. Thanks! ^-^

**Comment by CaliCastle** [comment]
Hi,

Doesn’t it support Landscape orientation already? Can you elaborate on the problem here in a little bit more details? Thanks!

**Comment by LayChan** [comment]
![simulator screen shot - iphone x - 2018-09-11 at 12 51 03](https://user-images.githubusercontent.com/15124524/45338759-6dc8ec80-b5c1-11e8-97d1-543cd57fa0c3.png)
![simulator screen shot - iphone x - 2018-09-11 at 12 51 10](https://user-images.githubusercontent.com/15124524/45338760-6dc8ec80-b5c1-11e8-873f-a4b701929a65.png)

**Comment by CaliCastle** [comment]
@LayChan did you get a chance to update to the newest version? (v2.1.1) this was fixed in that update

**Comment by LayChan** [comment]
OK, thanks
