### ISSUE TITLE
Error While Archive Process

### ISSUE THREAD

**Issue by lendra85** [CaliCastle/PopMenu#15]
## ✔️ Issue Checklist

- [✔️ ] I have updated PopMenu to the latest version.
- [ ✔️] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [ ] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [ ] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## 💻 Environment

- **iOS Version**: [12]
- **Xcode Version**: [10]
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Simulator?**: [YES] or [NO]

**Comment by CaliCastle** [comment]
Hi, can you elaborate on the issue?

**Comment by CaliCastle** [comment]
Closing for now as no more details are given here

**Comment by lendra85** [comment]
I am sorry for late response, here is the error i can get as below:

error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 141error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 5352error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 10569error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 15790error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 21027error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 26250error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 31468error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 36705error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 41930error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 47150error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 52368error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 57588error: error reading dependency file '/Users/sailendra/Library/Developer/Xcode/DerivedData/IDNTimes-cxbxvybuwjrpcdfcqbshvmexkiac/Build/Intermediates.noindex/ArchiveIntermediates/	/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/NewPopMenu.build/Objects-normal/arm64/NewPopMenu-master.d': missing ':' following rule at position 62805Command CompileSwiftSources emitted errors but did not return a nonzero exit code to indicate failure
