### ISSUE TITLE
App crash on hooking popup manager with UIBarButtonItem in navigation bar

### ISSUE THREAD

**Issue by c-sharma** [CaliCastle/PopMenu#16]
## ✔️ Issue Checklist

- [x] I have updated PopMenu to the latest version.
- [x] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## ✍🏻 Issue Description

App crashing when the popup manager is attached to UIBarButtonItem in the navigation bar. The menu click then loads the corresponding screens on the navigation stack. The first 2-3 times successful transition takes place, however when coming back to the base screen causes the crash. And the AppDelegate.swift shows the crash showing signal SIGABRT.

Pasting below the backtrace:
<img width="1280" alt="screen shot 2018-10-28 at 7 32 03 pm" src="https://user-images.githubusercontent.com/9255148/47616863-2c948980-dae8-11e8-9a1d-3c6698cd42dd.png">

* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x0000000110460eb6 libsystem_kernel.dylib`__abort_with_payload + 10
    frame #1: 0x000000011045b2b8 libsystem_kernel.dylib`abort_with_payload_wrapper_internal + 89
    frame #2: 0x000000011045b25f libsystem_kernel.dylib`abort_with_reason + 22
    frame #3: 0x000000010cbde1f5 libobjc.A.dylib`_objc_fatalv(unsigned long long, unsigned long long, char const*, __va_list_tag*) + 108
    frame #4: 0x000000010cbde11e libobjc.A.dylib`_objc_fatal(char const*, ...) + 127
    frame #5: 0x000000010cbe6409 libobjc.A.dylib`lookUpImpOrForward + 645
    frame #6: 0x000000010cbf3814 libobjc.A.dylib`_objc_msgSend_uncached + 68
    frame #7: 0x0000000117633c5c UIKitCore`-[_UIButtonBarItemLayout initWithLayoutMetrics:barButtonItem:] + 148
    frame #8: 0x0000000117635c82 UIKitCore`-[_UIButtonBarItemGroupLayout _newLayoutForBarButtonItem:useGroupSizing:] + 255
    frame #9: 0x0000000117636003 UIKitCore`-[_UIButtonBarItemGroupLayout _configure] + 816
    frame #10: 0x0000000117632e8c UIKitCore`-[_UIButtonBarLayout configure] + 60
    frame #11: 0x0000000117632f27 UIKitCore`-[_UIButtonBarLayout addLayoutViews:layoutGuides:constraintsToActivate:constraintsToDeactivate:] + 95
    frame #12: 0x0000000116e0d778 UIKitCore`-[_UIButtonBar _layoutBar] + 1869
    frame #13: 0x0000000116e10218 UIKitCore`-[_UIButtonBarStackView updateConstraints] + 48
    frame #14: 0x0000000116c86254 UIKitCore`-[UIView(AdditionalLayoutSupport) _sendUpdateConstraintsIfNecessaryForSecondPass:] + 161
    frame #15: 0x0000000116c86829 UIKitCore`-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 1245
    frame #16: 0x0000000116c866ad UIKitCore`-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 865
    frame #17: 0x000000010c7ec55a Foundation`-[NSISEngine withBehaviors:performModifications:] + 110
    frame #18: 0x0000000116c87046 UIKitCore`__100-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]_block_invoke + 85
    frame #19: 0x0000000116c85876 UIKitCore`-[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:] + 104
    frame #20: 0x0000000116c86bce UIKitCore`-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 155
    frame #21: 0x0000000116c87c82 UIKitCore`-[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:] + 374
    frame #22: 0x00000001174a27a5 UIKitCore`-[UIView(Hierarchy) layoutBelowIfNeeded] + 1094
    frame #23: 0x000000011775ca95 UIKitCore`-[_UINavigationBarContentView recordToStateForTransition:] + 55
    frame #24: 0x000000011776d199 UIKitCore`-[_UINavigationBarTransitionContext recordUpdates:] + 168
    frame #25: 0x00000001177954eb UIKitCore`-[_UINavigationBarVisualProviderModernIOS _performAnimationWithTransitionCompletion:transition:] + 644
    frame #26: 0x000000011705e381 UIKitCore`-[UINavigationBar _popNavigationItemWithTransitionAssistant:] + 215
    frame #27: 0x000000011705e00b UIKitCore`-[UINavigationBar _popNavigationItemWithTransition:] + 447
    frame #28: 0x000000011705dd8a UIKitCore`-[UINavigationBar popNavigationItemAnimated:] + 169
    frame #29: 0x0000000117796fec UIKitCore`-[_UINavigationBarVisualProviderModernIOS navigationBarContentViewDidTriggerBackAction:fromBackButtonItem:] + 259
    frame #30: 0x000000011775803b UIKitCore`-[_UINavigationBarContentView __backButtonAction:] + 58
    frame #31: 0x0000000116da07c3 UIKitCore`-[UIApplication sendAction:to:from:forEvent:] + 83
    frame #32: 0x0000000116ed8e85 UIKitCore`-[UIControl sendAction:to:forEvent:] + 67
    frame #33: 0x0000000116ed91a2 UIKitCore`-[UIControl _sendActionsForEvents:withEvent:] + 450
    frame #34: 0x0000000116ed9316 UIKitCore`-[UIControl _sendActionsForEvents:withEvent:] + 822
    frame #35: 0x0000000116ed80e6 UIKitCore`-[UIControl touchesEnded:withEvent:] + 583
    frame #36: 0x00000001175b3334 UIKitCore`-[UIWindow _sendTouchesForEvent:] + 2729
    frame #37: 0x00000001175b4a30 UIKitCore`-[UIWindow sendEvent:] + 4080
    frame #38: 0x0000000116dbae10 UIKitCore`-[UIApplication sendEvent:] + 352
    frame #39: 0x0000000116cf30d0 UIKitCore`__dispatchPreprocessedEventFromEventQueue + 3024
    frame #40: 0x0000000116cf5cf2 UIKitCore`__handleEventQueueInternal + 5948
    frame #41: 0x000000010da1fb31 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #42: 0x000000010da1f3a3 CoreFoundation`__CFRunLoopDoSources0 + 243
    frame #43: 0x000000010da19a4f CoreFoundation`__CFRunLoopRun + 1263
    frame #44: 0x000000010da19221 CoreFoundation`CFRunLoopRunSpecific + 625
    frame #45: 0x00000001149ed1dd GraphicsServices`GSEventRunModal + 62
    frame #46: 0x0000000116d9f115 UIKitCore`UIApplicationMain + 140
  * frame #47: 0x000000010b2c72e4 iOS-Sectona`main at AppDelegate.swift:14
    frame #48: 0x0000000110122551 libdyld.dylib`start + 1

## 💻 Environment

- **iOS Version**: iOS 12, Swift 4
- **Xcode Version**: v10.0
- **Device(s)**: iPhone 6s
- **Simulator?**: [YES]

**Comment by CaliCastle** [comment]
Tested several times, no crashes whatsoever on my end here, would you provide your code so I can investigate further? (that is if this is still a valid issue) closing for now
