### ISSUE TITLE
Click on the way

### ISSUE THREAD

**Issue by kmheike** [CaliCastle/PopMenu#17]
你好我要在控制器调用 你的点击方法知道在哪被点击了请问在哪调用找半天没找到，我用的是文字的这个 ，Hello, I'm going to call your click method on the controller. I know where it was clicked，I'm using this one in writing

**Comment by CaliCastle** [comment]
在`控制器`里哪里调用显示都可以的，没有限制，如果不传`sourceView`的参数的话就会在屏幕中央显示菜单
