### ISSUE TITLE
How to popmenu didDeselect action ?

### ISSUE THREAD

**Issue by DGP13** [CaliCastle/PopMenu#23]
I'm open agin popmenu it's show me previous  select action. How to diddeselect popmenu action ?

**Comment by CaliCastle** [comment]
Refer to documentation:
https://popmenu.calicastle.com/guide/#dismissal-callback

Example:
```swift
// The manager way
manager.popMenuDidDismiss = { selected in
    // `selected` is a bool indicating if a selection has been made

    if !selected {
        // When the user tapped outside of the menu
    }
}
```

**Comment by CaliCastle** [comment]
Or actually you should use View Controller methods instead (if you're using Manager, it's not recommended):
https://popmenu.calicastle.com/guide/#basic-usage-using-controller
