### ISSUE TITLE
can't set PopMenuActionColor

### ISSUE THREAD

**Issue by galblank** [CaliCastle/PopMenu#24]
## ✍🏻 Issue Description

this code is invalid since actionColor is an object and can't be set
`manager.popMenuAppearance.popMenuColor.actionColor = .green`

## 💻 Environment

- **iOS Version**: [iOS VERSION]
- **Xcode Version**: [XCODE VERSION]
10.1
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Simulator?**: ☑️

**Comment by CaliCastle** [comment]
You'll have to do:
```swift
manager.popMenuAppearance.popMenuColor.actionColor = .tint(.green)
```

sorry bout that in the documentation

**Comment by galblank** [comment]
Thank you!
