### ISSUE TITLE
是否可以设置偏移，因为我不想PopMenu挡住Button的位置：UIBarButtonItem

### ISSUE THREAD

**Issue by China77** [CaliCastle/PopMenu#31]
## ✔️ Issue Checklist

- [ ] I have updated PopMenu to the latest version.
lastest version 2.0+
- [ ] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [ ] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [ ] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## 💻 Environment

- **iOS Version**: [iOS VERSION]
IOS 11 Swift 4.2
- **Xcode Version**: [XCODE VERSION]
XCode 10.1
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Simulator?**: ☑️ or ❌

**Comment by China77** [comment]
Please Offset , THX :) 非好好用的控件! Good PopMenu

**Comment by CaliCastle** [comment]
感谢提出issue但是此问题已经重复了 #14 
This is a dupe of #14
