### ISSUE TITLE
Customize location

### ISSUE THREAD

**Issue by xSci** [CaliCastle/PopMenu#42]
## ✔️ Issue Checklist

- [x ] I have updated PopMenu to the latest version.
- [x ] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [ x] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [ x] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## ✍🏻 Issue Description

It is a very nice pop up menu, however, looks like the position is sticked to the center of the screen rather than being customized. It would be good if this can be an option. e.g. on the right top corner right below the navigation bar.

## 💻 Environment

- **iOS Version**: [iOS VERSION]
- **Xcode Version**: [XCODE VERSION]
- **Device(s)**: [INSERT DEVICE(S) HERE]
- **Simulator?**: ☑️ or ❌

**Comment by CaliCastle** [comment]
possible duplicate by #14

**Comment by CaliCastle** [comment]
Thanks for using PopMenu!
