### ISSUE TITLE
Set Item's Selection Style to none

### ISSUE THREAD

**Issue by nrshoudi** [CaliCastle/PopMenu#43]
## ✔️ Issue Checklist

- [x] I have updated PopMenu to the latest version.
- [x] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## 💻 Environment

- **iOS Version**: iOS11
- **Xcode Version**: 10.3
- **Device(s)**: [iPhone 6 and above]
- **Simulator?**: ☑️ 

How can I remove the dark background of an item when the user de-selecting it?
Or remove all the style of the item selection

<img width="248" alt="Screen Shot 2019-08-21 at 1 40 22 AM" src="https://user-images.githubusercontent.com/17602996/63389556-c4839c80-c3b4-11e9-9bd5-2f4c7da05023.png">

**Comment by CaliCastle** [comment]
I think this background issue only happens in iPhone Simulator, can you test the project in a real device?

**Comment by nrshoudi** [comment]
Yes, it's solved with the real device. Thank you!
