### ISSUE TITLE
Dismiss PopMenu Programmatically

### ISSUE THREAD

**Issue by BBITSDev** [CaliCastle/PopMenu#55]
## ✔️ Issue Checklist

- [x] I have updated PopMenu to the latest version.
- [x] I have read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I have read the [Documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I have searched for [GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

## ✍🏻 Issue Description
How to dismiss PopMenu programmatically? I am using PopMenuManager to show menu.

## 💻 Environment

- **iOS Version**: 13.5
- **Xcode Version**: 11.5
- **Device(s)**: Simulator
- **Simulator?**: ☑️ or ❌

**Comment by divyeshmakwana96** [comment]
PopMenu is just a `UIViewController`. You should be able to close is with `UIViewController`'s `dismiss` method.

**Comment by BBITSDev** [comment]
Thanks
