### ISSUE TITLE
[UI Enhancement] iconImageView renderingMode configurable to alwaysOriginal

### ISSUE THREAD

**Issue by kokitang** [CaliCastle/PopMenu#8]
I want to support colored image in the menu, so please give a variable to manage the renderingMode of iconImageView.

**Comment by CaliCastle** [comment]
Good idea, haven't thought of that, thanks!

**Comment by CaliCastle** [comment]
![simulator screen shot - iphone x - 2018-09-02 at 23 07 42](https://user-images.githubusercontent.com/10830749/44970131-04801400-af05-11e8-95ad-719ebf216310.png)

This will be fixed in the new update

**Comment by CaliCastle** [comment]
Hi,

The suggested enhancement is completed in v2.1.1, let me know if there's any issue or bug, thanks again!
