### ISSUE TITLE
PopMenuDefaultAction.iconWidthHeight is a static property

### ISSUE THREAD

**Issue by shalyf** [CaliCastle/PopMenu#9]
This is a cool popup menu, I like it, and I will use it in my project.
But when I add my icon image(size 18 pixel) to PopMenuDefaultAction, It looks ugly. The image is much bigger than I expected. So I looked at the source code and found a problem.

`PopMenuDefaultAction.iconWidthHeight` is a static property, I think it should be automatically calculated.
```
NSLayoutConstraint.activate([
                iconImageView.widthAnchor.constraint(equalToConstant: PopMenuDefaultAction.iconWidthHeight),
                iconImageView.heightAnchor.constraint(equalTo: iconImageView.widthAnchor),
                iconImageView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: PopMenuDefaultAction.iconLeftPadding),
                iconImageView.centerYAnchor.constraint(equalTo: view.centerYAnchor)
            ])
```

` iconImageView.widthAnchor` and `iconImageView.heightAnchor` should be automatically calculated based on the size of the image.

Now I am using a custom `PopMenuAction` named `PopMenuCustomAction` and modifying `PopMenuDefaultAction.iconWidthHeight` to 18 to resolve my problem.

Please fix this issue, Thanks.

**Comment by CaliCastle** [comment]
![simulator screen shot - iphone x - 2018-09-02 at 23 26 26](https://user-images.githubusercontent.com/10830749/44970649-a1dc4780-af07-11e8-9543-1534e62acdc1.png)

It'll be added to `PopMenuDefaultAction` and you can directly configure it like:

```swift
let action = PopMenuDefaultAction(title: "Some Title", image: UIImage(named: "blah"), color: .gray)
action.iconWidthHeight = 45
```

**Comment by CaliCastle** [comment]
Hi @shalyf,

The suggested enhancement is completed in v2.1.1, let me know if there's any issue or bug, thanks again!
